version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/Users/admin/Workspace/DeziDataServer
      - /Users/admin/Workspace/DeziDataServer/node_modules
    ports:
      - "3000:3000"